name: Daily Monitoring

on:
  schedule:
    - cron: '0 * * * *' # 매시간 실행
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests beautifulsoup4 lxml
      - name: Run Scraper
        run: python scraper.py
      - name: Commit changes
        run: |
          git config --global user.name "changsik-hwang"
          git config --global user.email "본인메일주소"
          git add data.json
          git commit -m "Update news data" || exit 0
          git push
